### ISSUE TITLE
[BUG] Hairline border is not work in safari

### ISSUE THREAD

**Issue by cocody** [30-seconds/30-seconds-of-css#110]
![](https://pic1.zhimg.com/v2-30cbb07ed7be3c740f6f9c2700f2a93b_r.jpg)

**Comment by atomiks** [comment]
It's already noted:

> *Chrome does not support subpixel values on border. Safari does not support subpixel values on box-shadow. Firefox supports subpixel values on both.

Technically it's a "Requires JavaScript" snippet and should have the JS required for cross-browser support. Feel free to make a PR

**Comment by cocody** [comment]
Need some more general method to replace it, like `transform: scaleY(0.5)`

**Comment by atomiks** [comment]
That distorts the element, not sure what other property would create a border..

I think you need to check Chromium (all browsers using the engine would not support subpixel values on `border` I think) and use `box-shadow`, otherwise use `border`. Firefox's box-shadow is not as perfect as the border.

```js
// Any better way?
const isChromium = [...navigator.plugins].some(plugin => /(Chrome|Chromium) PDF Viewer/i.test(plugin.name))

if (isChromium) {
  document.documentElement.classList.add('chromium')
}
```

```css
.el {
  border: 1px solid;
}

@media (min-resolution: 2dppx) {
  .el {
    border: 0.5px solid;
  }
  .chromium .el {
    box-shadow: 0 0 0 0.5px;
  }
}
```
