### ISSUE TITLE
[CSS/FEATURE] HTML5 audio/video player in a dark style

### ISSUE THREAD

**Issue by ZeroDot1** [30-seconds/30-seconds-of-css#91]
```css
video::-webkit-media-controls { 
filter: invert(1) grayscale(1) !important; 
opacity: " +transparency+ " !important; 
}
```
